Улучшена работа фаервола.     * Переработан фаервол под новую схему с auth, blocked, negbal списками     * xgesh теперь работает с сессиями     * Добавлен редирект через встроенный http сервер

diff --git a/usr/local/bin/xgesh b/usr/local/bin/xgesh
--- a/usr/local/bin/xgesh
+++ b/usr/local/bin/xgesh
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+PS4='+ ${BASH_SOURCE##*/}($LINENO): ${FUNCNAME:-}: '
 export PATH="$PATH:/usr/sbin/:/sbin/:/usr/local/sbin/:/usr/local/bin/"
 
 #set -eux
@@ -34,7 +34,7 @@ lock_shapers_dir="$shapers_dir/lock"
 exec 20>/var/lock/xge_iptables.lock
 exec 21>/var/lock/xge_class_id_allocate.lock
 row="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
-session_fields="ip username snat policy lists mac class_id state type terminate_cause tmp"
+session_fields="ip username snat rate lists mac class_id state type terminate_cause tmp"
 
 lists_prepare() {
 	for f in {2001..8998}; do
@@ -99,12 +99,70 @@ __session_dump() {
 	cat /var/lib/xge_sessions/*
 }
 
-session() {
-	session_cmd="$1"
-	shift
-	case "$session_cmd" in
-	info | dump | disconnect | start | stop | test | remove | list )
+__session_nat() {
+	local session_id="$1"
+	local action=add
+	[ "${2:-}" = "cancel" ] && action=del
+
+	if [ "$action" = "add" ]; then
+		snatip=${2:-0.0.0.0}
+		[ "$snatip" = "0.0.0.0" ] && { echo "Invalid snatip $snatip, skiped" ;  return 0; }
+		__snat_tree_add "$session_id" "$snatip"
+	else
+		snatip="$( __session_var_get $session_id snat )"
+		__snat_tree_del "$session_id" "$snatip"
+	fi
+
+	return $?
+
+}
+
+__session_redirect(){
+	local session_id="$1"
+	local list_name="$2"
+	local action=add
+	[ "${3:-}" = "cancel" ] && action=del
+	__ipset $action xge_${list_name}_list $session_id
+}
+
+## xgesh session $ip start $type
+## xgesh session $ip stop $cause
+## xgesh session $ip redirect negbal
+## xgesh session $ip redirect blocked
+## xgesh session $ip redirect negbal cancel
+## xgesh session $ip nat $snatip
+## xgesh session $ip nat cancel
+## xgesh session $ip rate set $rate_in $ceil_in $burst_in out $rate_out $ceil_out $burst_out
+## xgesh session $ip rate remove
+## xgesh session $ip disconnect
+## xgesh session $ip remove
+## xgesh session $ip info
+## xgesh session $ip test
+session(){
+	if [[ " dump list " == *" $1 "* ]]; then
+		session_cmd="$1"
 		__session_$session_cmd $@
+		return $?
+	fi
+	case "$2" in
+	info | disconnect | start | stop | test | remove | forward | redirect | nat | rate)
+		session_id="$1"
+		shift
+
+		session_cmd="$1"
+		shift
+
+		if [ "$session_id" = "0.0.0.0" ]; then
+			echo "Session id $session_id invalid"
+			return 1
+		fi
+
+		if [[ " start " != *" $session_cmd "* ]] && ! __session_exist $session_id; then
+			echo "Session $session_id not found"
+			echo "xgesh session <session_id> start"
+			return 1
+		fi
+		__session_$session_cmd $session_id $@
 		;;
 	* )
 		echo "bad subcommand: $session_cmd $@"
@@ -137,14 +195,16 @@ __session_update() {
 # __session_disconnect $ip
 #TODO: сбросить веб-авторизацию итд
 __session_disconnect() {
+	local session_id=$1
 	echo ${FUNCNAME//_/ } $@
-	if accel-cmd terminate ip $1; then
-		__session_stop $1
-		__session_update $1 terminate_cause 'CoA-Disconnect'
+	if accel-cmd terminate ip $session_id; then
+		__session_stop $session_id
+		__session_update $session_id terminate_cause 'CoA-Disconnect'
 	fi
 
 	if [ "$(__session_var_get $1 type)" = 'IPOE' ]; then
-		ip accept_list del $1
+		__session_stop $session_id
+		__session_update $session_id terminate_cause 'CoA-Disconnect'
 	fi
 }
 
@@ -154,6 +214,7 @@ __session_start() {
 	__session_update $session_id state UP
 	__session_update $session_id type $SESSION_TYPE
 	__session_update $session_id terminate_cause ''
+	__ipset add xge_auth_list $session_id
 }
 
 __session_stop() {
@@ -163,20 +224,29 @@ __session_stop() {
 	[ "$(__session_var_get $session_id state)" = "DOWN" ] && return 0 #for save 'CoA-Disconnect'
 	__session_update $session_id state DOWN
 	__session_update $session_id terminate_cause $2
+	__ipset del xge_auth_list $session_id
 
 }
 
 __session_remove() {
 	#TODO: убивать всё нах (if-down / radius-coa disconnect iptables/ipset)
-	set -x
-	local ip=$1
-	__session_disconnect $ip
-	rm -f $session_dir/$ip
-	set +x
+	local session_id=$1
+	__session_disconnect $session_id
+	__session_nat $session_id cancel
+	__session_redirect $session_id redirect negbal cancel
+	__session_redirect $session_id redirect blocked cancel
+	__shaper_del $session_id
+	# todo delete from all ipsets
+	rm -f $session_dir/$session_id
 }
 
 __session_test() {
 	session_test.sh $1
+}
+
+__session_exist(){
+	session_id="$1"
+	[ -f $session_dir/$session_id ]
 }
 
 # __session_var_get session_id var
@@ -207,23 +277,26 @@ __session_info() {
 	echo
 }
 
-policy() {
-	policy_cmd="$1"
+__session_rate() {
+	session_id=$1
 	shift
-	case $policy_cmd in
+
+	rate_cmd=$1
+	shift
+	case $rate_cmd in
 	set | remove )
-		__policy_$policy_cmd ${@//null/0}
+		__rate_$rate_cmd $session_id ${@//null/0}
 		;;
 	* )
-		echo "bad subcommand: $policy_cmd ${@//null/0}"
+		echo "bad subcommand: $rate_cmd $session_id ${@//null/0}"
 		return 1
 		;;
 	esac
 }
 
-# __policy_set 10.128.0.75 in 1000 2000 3000 out 1000 2000 3000
-__policy_set() {
-	echo ${FUNCNAME//_/ } $@
+# __rate_set 10.128.0.75 in 1000 2000 3000 out 1000 2000 3000
+__rate_set() {
+	# echo ${FUNCNAME//_/ } $@
 	local ip="$1"
 	shift
 
@@ -235,40 +308,40 @@ __policy_set() {
 	read rate_in ceil_in burst_in tmp_in <<< "$in"
 	read rate_out ceil_out burst_out tmp_out <<< "$out"
 
+	[ "$rate_out" = "0" ] && rate_out=''
+	[ "$ceil_out" = "0" ] && ceil_out=''
 	rate_in=${rate_in:-512}
 	ceil_in=${ceil_in:-$rate_in}
-	burst_in=${burst_in:-0}
-	rate_out=${rate_out:-512}
-	ceil_out=${ceil_out:-$rate_out}
-	burst_out=${burst_out:-0}
+	burst_in=${burst_in:-10000}
+	rate_out=${rate_out:-$rate_in}
+	ceil_out=${ceil_out:-$ceil_in}
+	burst_out=${burst_out:-10000}
 
 	if [ $ceil_in = '-1' -o "$ceil_in" = '0' ] && [ $ceil_out = '-1' -o "$ceil_out" = '0' ]; then
-		echo "Remove policy for $ip because of ceil"
-		__policy_remove "$ip"
+		echo "Remove rate for $ip because of ceil"
+		__rate_remove "$ip"
 		return 0
 	fi
 
 	if [ $rate_in = '-1' -o "$rate_in" = '0' ] && [ $rate_out = '-1' -o "$rate_out" = '0' ]; then
-		echo "Remove policy for $ip because of rate"
-		__policy_remove "$ip"
+		echo "Remove rate for $ip because of rate"
+		__rate_remove "$ip"
 		return 0
 	fi
 
 
 	__shaper_add $ip $rate_in $ceil_in $burst_in $rate_out $ceil_out $burst_out
-	[ "$?" = '0' ] && __session_update $ip policy "in $rate_in $ceil_in $burst_in out $rate_out $ceil_out $burst_out"
+	[ "$?" = '0' ] && __session_update $ip rate "in $rate_in $ceil_in $burst_in out $rate_out $ceil_out $burst_out"
 }
 
-# __policy_remove 10.128.0.75
-__policy_remove() {
+# __rate_remove 10.128.0.75
+__rate_remove() {
 	echo ${FUNCNAME//_/ } $@
 	local ip="$1"
 	shift
 	__shaper_del $ip || return $?
-	[ "$?" = '0' ] && __session_update $ip policy ''
+	[ "$?" = '0' ] && __session_update $ip rate ''
 }
-
-
 
 # __class_id_allocate $ip
 __class_id_allocate() {
@@ -328,7 +401,7 @@ __shaper_add() {
 	if [ -z $class_id ]; then
 		class_id="$(__class_id_allocate $ip)" || return 2
 	fi
-	[ -f $free_shapers_dir/$class_id ] && mv $free_shapers_dir/$class_id $lock_shapers_dir/$class_id
+	[ -f $free_shapers_dir/$class_id ] && mv $free_shapers_dir/$class_id $lock_shapers_dir/$class_id #wtf?
 	quantum_out=$(( $ceil_out*1000/80 ));
 	[ "$quantum_out" -gt 200000 ] && quantum_out=200000
 	[ "$quantum_out" -lt 1500   ] && quantum_out=1500
@@ -375,26 +448,6 @@ __shaper_del() {
 }
 #REFACTORING END
 
-ip() {
-	echo "$FUNCNAME $@"
-	local list="$1"
-	local action="$2"
-	local ip="$3"
-	[ "$action" = '1' ] && action='add'
-	[ "$action" = '0' ] && action='del'
-	[ "${list:0:4}" != "xge_" ] && list=xge_$list
-
-	if  [ "$#" -ge '3' -a "$list" = 'xge_snat' ]; then
-		snatip=${4:-0.0.0.0}
-		__snat_tree_del "$ip" "$snatip"
-		if [ "$action" = 'add' -o "$action" = 'del' ]; then
-			__snat_tree_$action "$ip" "$snatip"
-			return $?
-		fi
-	fi
-	__ipset $action $list $ip
-}
-
 # 	__ipset $action $list $ip
 __ipset() {
 	local session_id=$3
@@ -412,7 +465,7 @@ __ipset() {
 
 	if [ "$1" = 'del' ]; then
 		if ! ipset -q test $2 $3; then
-			echo " $3 already isn't in $2 "
+			echo " $3 isn't in $2 "
 		else
 			ipset $@ || return $?
 		fi
@@ -450,9 +503,9 @@ __snat_tree_add() {
 }
 
 __snat_tree_del() {
-	__snat_cache_refresh
 	NAT_CHAIN=$(__nat_chain_eval $1)
 	iptables -t nat -D $NAT_CHAIN -s $1 -j SNAT --to-source $2 &>/dev/null
+	__snat_cache_refresh
 	while read OLD_NUMBER_SNAT t t t t t to t; do
 		[ -z "$OLD_NUMBER_SNAT" ] && break
 		iptables -t nat -D $NAT_CHAIN -s $1 -j SNAT --to-source ${to//to:/} 2>/dev/null
@@ -494,52 +547,47 @@ __mac_show() {
 
 help() {
 	echo 'Usage: xgesh OBJECT { COMMAND }'
-	echo '       where  OBJECT := { ip | filter | nat | mangle | session | policy | mac }'
+	echo '       where  OBJECT := { session | mac }'
 	echo '	       and  COMMANDS := {'
-	echo '		    # access'
-	echo '		    	# allow forward traffic (give access:)'
-	echo '			    xgesh ip accept_list add <abonent ip>'
-	echo '			    xgesh ip accept_list 1 <abonent ip>'
-	echo '		    	# remove forward traffic (give access:)'
-	echo '			    xgesh ip accept_list del <abonent ip>'
-	echo '			    xgesh ip accept_list 0 <abonent ip>'
-	echo '		    # nat'
-	echo '		    	# add snat address to user:'
-	echo '			    xgesh ip snat add <abonent ip> <abonent snat ip>'
-	echo '			    xgesh ip snat 0 <abonent ip> <abonent snat ip>'
-	echo '		    	# remove snat address from user:'
-	echo '			    xgesh ip snat del <abonent ip>'
-	echo '			    xgesh ip snat add <abonent ip> 0.0.0.0'
-	echo '			    xgesh ip snat 0 <abonent ip>'
-	echo '			    xgesh ip snat 1 <abonent ip> 0.0.0.0'
+#TODO remove mac to session?
 	echo '		    # mac'
 	echo '		    	# set mac binding:'
 	echo '			    xgesh mac set <abonent ip> <MAC>'
 	echo '		    	# set mac binding:'
 	echo '			    xgesh mac remove <abonent ip>'
-	echo '		    # shapers'
-	echo '		    	# set shaper:'
-	echo '			    xgesh policy set <abonent ip> in <RATE_IN> <CEIL_IN> <BURST_IN> out <RATE_OUT> <CEIL_OUT> <BURST_OUT>'
-	echo '			    xgesh policy set <abonent ip> in <RATE_IN> <CEIL_IN> out <RATE_OUT> <CEIL_OUT>'
-	echo '			    xgesh policy set <abonent ip> in <RATE_IN> out <RATE_OUT>'
-	echo '		    	# remove forward traffic (give access:)'
-	echo '			    xgesh policy remove <abonent ip>'
-	echo '		    # redirects'
-	echo '			# add redirect to negative balance page'
-	echo '			    xgesh ip negbal_list add <abonent ip>'
-	echo '			    xgesh ip negbal_list 1 <abonent ip>'
-	echo '			# remove redirect to negative balance page'
-	echo '			    xgesh ip negbal_list del <abonent ip>'
-	echo '			    xgesh ip negbal_list 0 <abonent ip>'
 	echo '		    # sessions'
 	echo '			# list of all sessions'
 	echo '			    xgesh session list'
 	echo '			# dump of all sessions'
 	echo '			    xgesh session dump'
 	echo '			# fast info about session'
-	echo '			    xgesh session info <abonent ip>'
+	echo '			    xgesh session <session_id> info'
 	echo '			# session diagnostic, getting info from iptables/ipset/tc/etc, slowly'
-	echo '			    xgesh session test <abonent ip>'
+	echo '			    xgesh session <session_id> test'
+	echo '			#create new session'
+	echo '                      session <session_id> start <type>'
+	echo '			#set session state DOWN'
+	echo '                      session <session_id> stop <stop_cause>'
+	echo '			#set session redirect type'
+	echo '                      session <session_id> redirect <redirect_type>'
+	echo '			#remove session redirect'
+	echo '                      session <session_id> redirect <redirect_type> cancel'
+	echo '			#set session snat'
+	echo '                      session <session_id> nat <snatip>'
+	echo '			#remove session snat'
+	echo '                      session <session_id> nat cancel'
+	echo '			#set session rates'
+	echo '                      session <session_id> rate set <rate_in> <ceil_in> <burst_in> out <rate_out> <ceil_out> <burst_out>'
+	echo '                      session <session_id> rate set <rate_in> <ceil_in> out <rate_out> <ceil_out>'
+	echo '                      session <session_id> rate set <rate_in> out <rate_out>'
+	echo '			#remove session retes'
+	echo '                      session <session_id> rate remove'
+	echo '			#diconnect session'
+	echo '                      session <session_id> disconnect'
+	echo '			#remove session from nas'
+	echo '                      session <session_id> remove'
+
+
 }
 
 cmd() {
@@ -551,7 +599,8 @@ cmd() {
 	[ "$cmd" = 'help' ] && session_lock='0000000000000000000'
 	session_lock=/var/lock/xge_${session_lock%% *}.lock
 	case $cmd in
-	ip | filter | nat | session | policy | mac | help )
+	#ip | filter | nat | session | rate | mac | help )
+	session | mac)
 		exec 22>$session_lock
 		__session_id_lock
 		$cmd $@
